// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from artists_panel_info_callback.djinni

package com.bytedance.djinni;

import com.snapchat.djinni.Outcome;

import androidx.annotation.NonNull;

public abstract class OutcomeCallback<R, E> {
    public abstract void callback(@NonNull Outcome<R, E> r);
}
